/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.essar.screens;

import com.essar.dao.SalesDAO;
import com.essar.dao.StockDAO;
import com.essar.dao.SupplierDAO;
import com.essar.pojos.SalesView;
import com.essar.pojos.Stock;
import com.essar.pojos.Supplier;
import com.essar.suggestion.SuggestionUtility;
import com.essar.utils.QueryStrings;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rahumathulla
 */
public class StockAudit extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Stock
     */
    long stockId=0;
    DecimalFormat df = new DecimalFormat("####.##");
    Stock stock = null;
    double gSalesPercentage = 0;
    double gStockAvailable = 0;
    DefaultTableModel salesModel = null;
    public StockAudit() {
        initComponents();
        initializeForm();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/tienda.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mitDelete = new javax.swing.JMenuItem();
        mitView = new javax.swing.JMenuItem();
        mnuTable = new javax.swing.JPopupMenu();
        pnlStockEntry = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtHSNCode = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        txtUnitPrice = new javax.swing.JTextField();
        txtGstPercentage = new javax.swing.JTextField();
        txtGstAmount = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        lblUnitPrice3 = new javax.swing.JLabel();
        lblUnitPrice2 = new javax.swing.JLabel();
        lblUnitPrice = new javax.swing.JLabel();
        lblAvailableQty = new javax.swing.JLabel();
        cmdReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblDirectStockEntry = new javax.swing.JLabel();
        lblPuchase = new javax.swing.JLabel();
        lblCurrentStock = new javax.swing.JLabel();
        lblSales = new javax.swing.JLabel();
        txtDirectStockEntry = new javax.swing.JLabel();
        txtPurchase = new javax.swing.JLabel();
        txtSales = new javax.swing.JLabel();
        txtCurrentStock = new javax.swing.JLabel();
        lblDifference = new javax.swing.JLabel();
        txtDifference = new javax.swing.JLabel();
        lblSummaryIcon = new javax.swing.JLabel();
        lblPossibleReasons = new javax.swing.JLabel();
        panSalesView = new javax.swing.JScrollPane();
        tblSalesView = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();

        mitDelete.setText("jMenuItem1");

        mitView.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stock Audit");
        setExtendedState(6);

        pnlStockEntry.setBorder(javax.swing.BorderFactory.createTitledBorder("Item Details"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("HSN Code");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Commodity/Item Name");

        txtHSNCode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtHSNCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHSNCodeActionPerformed(evt);
            }
        });
        txtHSNCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHSNCodeKeyPressed(evt);
            }
        });

        txtItemName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtItemName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtItemNameFocusLost(evt);
            }
        });
        txtItemName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtItemNameMouseClicked(evt);
            }
        });
        txtItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemNameActionPerformed(evt);
            }
        });
        txtItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtItemNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtItemNameKeyTyped(evt);
            }
        });

        txtUnitPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUnitPrice.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitPriceActionPerformed(evt);
            }
        });

        txtGstPercentage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtGstPercentage.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtGstPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGstPercentageActionPerformed(evt);
            }
        });

        txtGstAmount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtGstAmount.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtGstAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGstAmountActionPerformed(evt);
            }
        });

        lblQuantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblQuantity.setText("Quantity");

        lblUnitPrice3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUnitPrice3.setText("GST Amt");

        lblUnitPrice2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUnitPrice2.setText("GST%");

        lblUnitPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUnitPrice.setText("Unit Price");

        lblAvailableQty.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAvailableQty.setForeground(new java.awt.Color(0, 102, 0));
        lblAvailableQty.setText("00");

        cmdReset.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset_small.png"))); // NOI18N
        cmdReset.setMnemonic('R');
        cmdReset.setText("Reset");
        cmdReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStockEntryLayout = new javax.swing.GroupLayout(pnlStockEntry);
        pnlStockEntry.setLayout(pnlStockEntryLayout);
        pnlStockEntryLayout.setHorizontalGroup(
            pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStockEntryLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmdReset)
                    .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHSNCode, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStockEntryLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtGstPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStockEntryLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUnitPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUnitPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGstAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvailableQty, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStockEntryLayout.setVerticalGroup(
            pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStockEntryLayout.createSequentialGroup()
                .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlStockEntryLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlStockEntryLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtHSNCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlStockEntryLayout.createSequentialGroup()
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUnitPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUnitPrice2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblUnitPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblQuantity)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGstPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlStockEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtGstAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAvailableQty)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(cmdReset))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Summary"));

        lblDirectStockEntry.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDirectStockEntry.setText("Direct Stock Entry");

        lblPuchase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPuchase.setText("Purchase");

        lblCurrentStock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCurrentStock.setText("Current Stock");

        lblSales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSales.setText("Sales");

        txtDirectStockEntry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDirectStockEntry.setForeground(new java.awt.Color(0, 102, 204));
        txtDirectStockEntry.setText("00");

        txtPurchase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPurchase.setForeground(new java.awt.Color(153, 51, 0));
        txtPurchase.setText("00");

        txtSales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSales.setForeground(new java.awt.Color(0, 102, 0));
        txtSales.setText("00");

        txtCurrentStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCurrentStock.setForeground(new java.awt.Color(0, 102, 102));
        txtCurrentStock.setText("00");

        lblDifference.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDifference.setText("Difference : ");

        txtDifference.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDifference.setForeground(new java.awt.Color(0, 153, 153));
        txtDifference.setText("00");

        lblSummaryIcon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSummaryIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thumbs_up.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblDirectStockEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDirectStockEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblSales, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSales, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblPuchase, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184)
                        .addComponent(lblDifference, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDifference, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblCurrentStock, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCurrentStock, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSummaryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(369, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDirectStockEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDirectStockEntry))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDifference, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPuchase, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPurchase)
                                .addComponent(lblDifference, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSales)
                            .addComponent(lblSales, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCurrentStock, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCurrentStock)))
                    .addComponent(lblSummaryIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        lblPossibleReasons.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblPossibleReasons.setText("Possible Reasons: ");

        panSalesView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panSalesViewMouseClicked(evt);
            }
        });
        panSalesView.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panSalesViewKeyPressed(evt);
            }
        });

        tblSalesView.setForeground(new java.awt.Color(0, 153, 153));
        tblSalesView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Bill Number", "Total Qty", "Bill Amount", "Cess", "Discount", "Net Amount", "Sales Date", " Status", "Sales Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSalesView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSalesViewMouseClicked(evt);
            }
        });
        tblSalesView.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblSalesViewKeyPressed(evt);
            }
        });
        panSalesView.setViewportView(tblSalesView);

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnCancel.setMnemonic('C');
        btnCancel.setText("Close");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStockEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblPossibleReasons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panSalesView))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlStockEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPossibleReasons, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panSalesView, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHSNCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHSNCodeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtItemName.requestFocus();
        }
    }//GEN-LAST:event_txtHSNCodeKeyPressed

    private void txtHSNCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHSNCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHSNCodeActionPerformed

    private void txtItemNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameFocusLost

    private void txtItemNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtItemNameMouseClicked

    }//GEN-LAST:event_txtItemNameMouseClicked

    private void txtItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemNameActionPerformed
        // TODO add your handling code here:
        System.out.println("---inside Action Peformed");
        performItemFieldAction();
        populateItemTransaction(stockId);
        
    }//GEN-LAST:event_txtItemNameActionPerformed

    private void txtItemNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameKeyPressed

    private void txtItemNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemNameKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            System.out.println("---inside item name enter");
            try{
                performItemFieldAction();
                populateItemTransaction(stockId);
            }
            catch(Exception e){
                System.out.println("Error Retrieving the item -"+e.getMessage());
            }
        }
    }//GEN-LAST:event_txtItemNameKeyReleased

    private void txtItemNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameKeyTyped

    private void txtUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitPriceActionPerformed

    private void txtGstPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGstPercentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGstPercentageActionPerformed

    private void txtGstAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGstAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGstAmountActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cmdResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdResetActionPerformed
        // TODO add your handling code here:
        initializeForm();
    }//GEN-LAST:event_cmdResetActionPerformed

    private void tblSalesViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSalesViewMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2 && tblSalesView.getSelectedRow() != -1){

        }
    }//GEN-LAST:event_tblSalesViewMouseClicked

    private void tblSalesViewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSalesViewKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_HOME && tblSalesView.getRowCount()>0){
            mnuTable.removeAll();
            //Add Existing
            mitView = new JMenuItem("View");
            mitView.addActionListener(this);
            mnuTable.add(mitView);
            //Add New
            mitDelete = new JMenuItem("Delete");
            mitDelete.addActionListener(this);
            mnuTable.add(mitDelete);

        }
        if(evt.getKeyCode()==KeyEvent.VK_END){
            //JOptionPane.showMessageDialog(this, "Hi");
            tblSalesView.changeSelection(salesModel.getRowCount()-1,1,false, false);
        }
    }//GEN-LAST:event_tblSalesViewKeyPressed

    private void panSalesViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panSalesViewMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            //syncDataFromViewToTable();

        }
    }//GEN-LAST:event_panSalesViewMouseClicked

    private void panSalesViewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panSalesViewKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            //syncDataFromViewToTable();
        }
    }//GEN-LAST:event_panSalesViewKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockAudit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockAudit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockAudit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockAudit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockAudit().setVisible(true);
            }
        });
    }
    
    public void initializeForm(){
        stockId =0;
        txtHSNCode.requestFocus();

        SupplierDAO supplierDAO = new SupplierDAO();
        renderDataIntoTable(supplierDAO.retrieveAll());
        SuggestionUtility.populateItemNames(this, txtItemName);
            //txtItemName.requestFocus();
        txtItemName.requestFocus();
        clearItemFields();

    }
    
    public void clearItemFields(){
        lblSummaryIcon.setIcon(null);
        lblPossibleReasons.setText("");
        txtItemName.setText("");
        txtDifference.setText("");
        txtCurrentStock.setText("");
        txtGstAmount.setText("");
        txtGstPercentage.setText("");
        txtHSNCode.setText("");
        txtPurchase.setText("");
        txtSales.setText("");
        txtUnitPrice.setText("");
    }
    
    public void enableFormElements(boolean flag){
        txtHSNCode.setEnabled(flag);
       
    }
    public boolean validateForm(){
        //btnSave.setText("Add");
        //btnSave.requestFocus();
        if(null == txtHSNCode.getText() || !(txtHSNCode.getText().matches("\\w+"))){
            JOptionPane.showMessageDialog(null, "HSN code "+txtHSNCode.getText() +" is not valid.");
            txtHSNCode.requestFocus();
            return false;
        }
        if(null == txtItemName.getText() || txtItemName.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Item name "+txtItemName.getText() +" is not valid.");
            txtItemName.requestFocus();
            return false;
        }
        
        return true;
    }
    
    
    public void populateItemTransaction(long itemId){
        System.out.println("Inside populateItemTransaction-------");
        String selectClause = "SELECT s.sales_id"
            + ", s.customer_name"
            + ", s.customer_name"
            + ", s.bill_number"
            + ", d.quantity"
            + ", d.net_amount"
            + ", s.cess"
            + ", s.discount"
            + ", s.payable_amount"
            + ", s.sales_date"
            + ", s.status  "
            + " from sales_details d "
            //+ " JOIN customer cust ON s.customer_id = cust.customer_id"
            + " JOIN sales s ON s.sales_id = d.sales_id WHERE 1=1 and d.item_id="+itemId;
        System.out.println("Query---"+selectClause);
        SalesDAO salesDAO = new SalesDAO();
        renderItemTransactionDataIntoTable(salesDAO.retrieveSalesByQuery(selectClause));
        
    }
    
    public void performItemFieldAction(){
        try{
            StockDAO stockDAO = null;
            //Stock
            stock = null;
            double dUnitGst=0.0;
            double dUnitSellingPrice=0.0;
            double dUnitDiscount=0.0;
            double dUnitPostGstPrice=0.0;

            if(!txtItemName.getText().equalsIgnoreCase(""))
            stockDAO = new StockDAO();
            stock = stockDAO.retrieveByName(txtItemName.getText().trim());
            stockId = stock.getItemId();
            txtHSNCode.setText(stock.getHsnCode());
            txtUnitPrice.setText(stock.getPurchasePrice()+"");

            //GST Amount Calculation
            txtGstPercentage.setText(stock.getGstPercentage()+"");
            dUnitGst = stock.getGstPercentage()*stock.getPurchasePrice()/100;
            txtGstAmount.setText(df.format(dUnitGst)+"");
            //txt.setText(df.format(dUnitGst)+"");

            //Price after Tax calculation
            dUnitPostGstPrice = dUnitGst +stock.getPurchasePrice();

            //Discount calculation
            if(stock.getMrp()>0){

            }
            //dUnitDiscount = Double.parseDouble(stock.getDiscount())*Double.parseDouble(stock.getPurchasePrice())/100;

            //Selling Price calculation
            dUnitSellingPrice = dUnitPostGstPrice + dUnitPostGstPrice*stock.getMargin()/100;
            double tempPrice = dUnitSellingPrice;
            dUnitSellingPrice = dUnitSellingPrice * gSalesPercentage *0.01;// *.01 is equivalent to division by 100

            System.out.println("outside cust type loop");


            //txtSellingPrice.setText(df.format(dUnitSellingPrice)+"");
            //Stock Availability Check
            gStockAvailable = stock.getQuantity();
            lblAvailableQty.setText(gStockAvailable+"");
            txtHSNCode.setEnabled(false);
            txtGstPercentage.setEnabled(false);
            txtGstAmount.setEnabled(false);
            txtUnitPrice.setEnabled(false);
            
            List<Double> summaryList = null;
            stockDAO = new StockDAO();
            System.out.println("ITEM ID :" +stock.getItemId());
            summaryList = stockDAO.retrieveAuditSummary(stock.getItemId(), stock.getItemName());
            System.out.println("Summary Size :"+summaryList.size());
            if(summaryList.get(0)!= 0.1)
                txtDirectStockEntry.setText(summaryList.get(0)+"");
            else
                txtDirectStockEntry.setText("0");
            if(summaryList.get(1)!= 0.2)
                txtPurchase.setText(summaryList.get(1)+"");
            else
                txtPurchase.setText("0");
            if(summaryList.get(2)!= 0.3)
                txtSales.setText(summaryList.get(2)+"");
            else
                txtSales.setText("0");
            if(summaryList.get(3)!= 0.4)
                txtCurrentStock.setText(summaryList.get(3)+"");
            else
                txtCurrentStock.setText("0");
            
            Double difference = Double.parseDouble(txtDirectStockEntry.getText().toString())+
                    Double.parseDouble(txtPurchase.getText().toString())-
                    Double.parseDouble(txtCurrentStock.getText().toString())-
                    Double.parseDouble(txtSales.getText().toString());
            txtDifference.setText(difference+"");
            if(difference==0)
                lblSummaryIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thumbs_up.png")));
            else
                lblSummaryIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/recheck.png")));
            
            if(difference<0){
                lblPossibleReasons.setText("Possible Reasons: \n 1) Missed purchase entry or stock entry, \n 2) Sold more items than the Stock \n"
                                            + ", 3) Purchase/Stock was entered corresponding to a wrong item"
                                            );
            }else if(difference>0){
                lblPossibleReasons.setText("Possible Reasons: \n 1) Missed sales entry of the item, \n 2) Sold less than the actual quantity \n"
                                            + ", 3) Purchase/Stock was entered corresponding to this item by mistake"
                                            );
            }else{
                lblPossibleReasons.setText("");
            }
            cmdReset.requestFocus();
            
        }
        catch(Exception e){
            System.out.println("Error Retrieving the item -"+e.getMessage());
        }
    }
    
    public void renderDataIntoTable(List<Supplier> supplierList){

        
    }
    
    public void renderItemTransactionDataIntoTable(List<SalesView> salesViewList){

        salesModel = (DefaultTableModel) tblSalesView.getModel();
        salesModel.setRowCount(0);
        for(int i=0;i<salesViewList.size();i++){
            //salesModel.addRow(new Object[]{salesViewList.get(i).getCustomerName(), salesViewList.get(i).getBillNumber(),salesViewList.get(i).getBillAmount(),salesViewList.get(i).getCess(),salesViewList.get(i).getDiscount(), salesViewList.get(i).getPayableAmount(), salesViewList.get(i).getSalesDate(), salesViewList.get(i).getStatus()});
            salesModel.addRow(new Object[]{salesViewList.get(i).getCustomerName()
                    , salesViewList.get(i).getBillNumber()
                    , salesViewList.get(i).getQuantity()
                    , salesViewList.get(i).getBillAmount()
                    , salesViewList.get(i).getCess()
                    , salesViewList.get(i).getDiscount()
                    , salesViewList.get(i).getPayableAmount()
                    , salesViewList.get(i).getSalesDate()
                    , salesViewList.get(i).getStatus()
                    , salesViewList.get(i).getSalesId()});
        }       

    }   


    @Override
    public void actionPerformed(ActionEvent event) {
        try{
            JMenuItem menu = (JMenuItem) event.getSource();

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton cmdReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAvailableQty;
    private javax.swing.JLabel lblCurrentStock;
    private javax.swing.JLabel lblDifference;
    private javax.swing.JLabel lblDirectStockEntry;
    private javax.swing.JLabel lblPossibleReasons;
    private javax.swing.JLabel lblPuchase;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSales;
    private javax.swing.JLabel lblSummaryIcon;
    private javax.swing.JLabel lblUnitPrice;
    private javax.swing.JLabel lblUnitPrice2;
    private javax.swing.JLabel lblUnitPrice3;
    private javax.swing.JMenuItem mitDelete;
    private javax.swing.JMenuItem mitView;
    private javax.swing.JPopupMenu mnuTable;
    private javax.swing.JScrollPane panSalesView;
    private javax.swing.JPanel pnlStockEntry;
    private javax.swing.JTable tblSalesView;
    private javax.swing.JLabel txtCurrentStock;
    private javax.swing.JLabel txtDifference;
    private javax.swing.JLabel txtDirectStockEntry;
    private javax.swing.JTextField txtGstAmount;
    private javax.swing.JTextField txtGstPercentage;
    private javax.swing.JTextField txtHSNCode;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JLabel txtPurchase;
    private javax.swing.JLabel txtSales;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables
}
